import { Schedule, Section } from '../../models/schedule.model';

export const watchtowerComplete: Schedule = {
   name: "The Watchtower!",
   complete: false,
   sections: [
      {
         name: "2017",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "No. 1", complete: false, sections: [] },
               { name: "No. 2", complete: false, sections: [] },
               { name: "No. 3", complete: false, sections: [] },
               { name: "No. 4", complete: false, sections: [] },
               { name: "No. 5", complete: false, sections: [] },
               { name: "No. 6", complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January",   complete: false, sections: [] },
               { name: "February",  complete: false, sections: [] },
               { name: "March",     complete: false, sections: [] },
               { name: "April",     complete: false, sections: [] },
               { name: "May",       complete: false, sections: [] },
               { name: "June",      complete: false, sections: [] },
               { name: "July",      complete: false, sections: [] },
               { name: "August",    complete: false, sections: [] },
               { name: "September", complete: false, sections: [] },
               { name: "October",   complete: false, sections: [] },
               { name: "November",  complete: false, sections: [] },
               { name: "December",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January",   complete: false, sections: [] },
               { name: "February",  complete: false, sections: [] },
               { name: "March",     complete: false, sections: [] },
               { name: "April",     complete: false, sections: [] },
               { name: "May",       complete: false, sections: [] },
               { name: "June",      complete: false, sections: [] },
               { name: "July",      complete: false, sections: [] },
               { name: "August",    complete: false, sections: [] },
               { name: "September", complete: false, sections: [] },
               { name: "October",   complete: false, sections: [] },
               { name: "November",  complete: false, sections: [] },
               { name: "December",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2016",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "No. 1", complete: false, sections: [] },
               { name: "No. 2", complete: false, sections: [] },
               { name: "No. 3", complete: false, sections: [] },
               { name: "No. 4", complete: false, sections: [] },
               { name: "No. 5", complete: false, sections: [] },
               { name: "No. 6", complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January",   complete: false, sections: [] },
               { name: "February",  complete: false, sections: [] },
               { name: "March",     complete: false, sections: [] },
               { name: "April",     complete: false, sections: [] },
               { name: "May",       complete: false, sections: [] },
               { name: "June",      complete: false, sections: [] },
               { name: "July",      complete: false, sections: [] },
               { name: "August",    complete: false, sections: [] },
               { name: "September", complete: false, sections: [] },
               { name: "October",   complete: false, sections: [] },
               { name: "November",  complete: false, sections: [] },
               { name: "December",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January",   complete: false, sections: [] },
               { name: "February",  complete: false, sections: [] },
               { name: "March",     complete: false, sections: [] },
               { name: "April",     complete: false, sections: [] },
               { name: "May",       complete: false, sections: [] },
               { name: "June",      complete: false, sections: [] },
               { name: "July",      complete: false, sections: [] },
               { name: "August",    complete: false, sections: [] },
               { name: "September", complete: false, sections: [] },
               { name: "October",   complete: false, sections: [] },
               { name: "November",  complete: false, sections: [] },
               { name: "December",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2015",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2014",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2013",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2012",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2011",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Simplified", complete: false, sections: [
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2010",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2009",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2008",
         complete: false,
         sections: [
            { name: "Public", complete: false, sections: [
               { name: "January 1",    complete: false, sections: [] },
               { name: "February 1",   complete: false, sections: [] },
               { name: "March 1",      complete: false, sections: [] },
               { name: "April 1",      complete: false, sections: [] },
               { name: "May 1",        complete: false, sections: [] },
               { name: "June 1",       complete: false, sections: [] },
               { name: "July 1",       complete: false, sections: [] },
               { name: "August 1",     complete: false, sections: [] },
               { name: "September 1",  complete: false, sections: [] },
               { name: "October 1",    complete: false, sections: [] },
               { name: "November 1",   complete: false, sections: [] },
               { name: "December 1",   complete: false, sections: [] },
            ] },
            { name: "Study", complete: false, sections: [
               { name: "January 15",   complete: false, sections: [] },
               { name: "February 15",  complete: false, sections: [] },
               { name: "March 15",     complete: false, sections: [] },
               { name: "April 15",     complete: false, sections: [] },
               { name: "May 15",       complete: false, sections: [] },
               { name: "June 15",      complete: false, sections: [] },
               { name: "July 15",      complete: false, sections: [] },
               { name: "August 15",    complete: false, sections: [] },
               { name: "September 15", complete: false, sections: [] },
               { name: "October 15",   complete: false, sections: [] },
               { name: "November 15",  complete: false, sections: [] },
               { name: "December 15",  complete: false, sections: [] },
            ] },
         ]
      },
      {
         name: "2007",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2006",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2005",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2004",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2003",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2002",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2001",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
      {
         name: "2000",
         complete: false,
         sections: [
            { name: "January 1",    complete: false, sections: [] },
            { name: "January 15",   complete: false, sections: [] },
            { name: "February 1",   complete: false, sections: [] },
            { name: "February 15",  complete: false, sections: [] },
            { name: "March 1",      complete: false, sections: [] },
            { name: "March 15",     complete: false, sections: [] },
            { name: "April 1",      complete: false, sections: [] },
            { name: "April 15",     complete: false, sections: [] },
            { name: "May 1",        complete: false, sections: [] },
            { name: "May 15",       complete: false, sections: [] },
            { name: "June 1",       complete: false, sections: [] },
            { name: "June 15",      complete: false, sections: [] },
            { name: "July 1",       complete: false, sections: [] },
            { name: "July 15",      complete: false, sections: [] },
            { name: "August 1",     complete: false, sections: [] },
            { name: "August 15",    complete: false, sections: [] },
            { name: "September 1",  complete: false, sections: [] },
            { name: "September 15", complete: false, sections: [] },
            { name: "October 1",    complete: false, sections: [] },
            { name: "October 15",   complete: false, sections: [] },
            { name: "November 1",   complete: false, sections: [] },
            { name: "November 15",  complete: false, sections: [] },
            { name: "December 1",   complete: false, sections: [] },
            { name: "December 15",  complete: false, sections: [] },
         ]
      },
   ],
};