import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';

@Injectable()
export class KingsService {
   getKings() {
      return Observable.create(observer => {
         observer.next(kings);
      });
   }
}

let kings: any[] = [
  {
    "kingNumber": 1,
    "kingName": "Re·ho·boʹam",
    "kingNamePlain": "Rehoboam",
    "age": 41,
    "startReignYear": "997 B.C.E.",
    "endReignYear": "980 B.C.E.",
    "highPriests": ["Zadok"],
    "chosenOffspring": "A·biʹjah",
    "prophets": [
      "Shemaiah",
      "Id·do"
    ],
    "sons": [
       "A·biʹjah",
       "Je'ush",
       "Shem·a·riʹah",
       "Zaʹham",
       "Atʹtai",
       "Ziʹza",
       "She·loʹmith",
       "(21 other sons)"
    ],
  },
  {
    "kingNumber": 2,
    "kingName": "A·biʹjah",
    "kingNamePlain": "Abijah",
    "startReignYear": "980 B.C.E.",
    "endReignYear": "978 B.C.E.",
    "highPriests": ["Zadok"],
    "chosenOffspring": "Aʹsa",
    "prophets": ["Id·do"],
    "sons": [
      "Aʹsa",
      "(21 other sons)"
    ],
  },
  {
    "kingNumber": 3,
    "kingName": "Aʹsa",
    "kingNamePlain": "Asa",
    "startReignYear": "978 B.C.E.",
    "endReignYear": "937 B.C.E",
    "highPriests": ["Zadok"],
    "chosenOffspring": "Je·hoshʹa·phat",
    "prophets": ["Az·a·riʹah", "Oded", "Hanani","Jehu (son of Hanani)", "Elijah", "Micaiah"],
    "sons": [
      "Je·hoshʹa·phat"
    ],
  },
  {
    "kingNumber": 4,
    "kingName": "Je·hoshʹa·phat",
    "kingNamePlain": "Jehoshaphat",
    "startReignYear": "937 B.C.E.",
    "endReignYear": "913 B.C.E.",
    "highPriests": ["Amariah"],
    "chosenOffspring": "Je·hoʹram",
    "prophets": ["Jehu (son of Hanani)","Eliezer", "Jahaziel", "Elijah", "Elishah"],
    "sons": [
      "Je·hoʹram",
      "Az·a·riʹah",
      "Je·hiʹel",
      "Zech·a·riʹah",
      "Miʹcha·el",
      "Sheph·a·tiʹah"
    ],
  },
  {
    "kingNumber": 5,
    "kingName": "Je·hoʹram",
    "kingNamePlain": "Jehoram",
    "age": 32,
    "startReignYear": "913 B.C.E.",
    "endReignYear": "c. 906 B.C.E.",
    "highPriests": ["Amariah"],
    "chosenOffspring": "A·ha·ziʹah",
    "prophets": ["Elijah", "Elishah"],
    "sons": [
      "A·ha·ziʹah"
    ],
  },
  {
    "kingNumber": 6,
    "kingName": "A·ha·ziʹah",
    "kingNamePlain": "Ahaziah",
    "age": 22,
    "startReignYear": "c. 906 B.C.E.",
    "endReignYear": "c. 905 B.C.E.",
    "highPriests": ["Je·hoiʹa·da"],
    "chosenOffspring": "Je·hoʹash",
    "prophets": ["E·liʹjah","E·liʹshah"],
    "sons": ["Je·hoʹash"],
  },
  {
    "kingNumber": 7,
    "kingName": "Ath·a·liʹah",
    "kingNamePlain": "Athaliah",
    "startReignYear": "c. 905 B.C.E.",
    "endReignYear": "898 B.C.E.",
    "highPriests": ["Je·hoiʹa·da"],
    "chosenOffspring": null,
    "prophets": ["E·liʹshah"],
    "sons": [],
  },
  {
    "kingNumber": 8,
    "kingName": "Je·hoʹash",
    "kingNamePlain": "Jehoash",
    "age": 7,
    "startReignYear": "898 B.C.E.",
    "endReignYear": "858 B.C.E.",
    "highPriests": ["Je·hoiʹa·da"],
    "chosenOffspring": "Am·a·ziʹah",
    "prophets": ["E·liʹshah"],
    "sons": ["Am·a·ziʹah"],
  },
  {
    "kingNumber": 9,
    "kingName": "Am·a·ziʹah",
    "kingNamePlain": "Amaziah",
    "age": 25,
    "startReignYear": "858 B.C.E.",
    "endReignYear": "829 B.C.E.",
    "highPriests": ["Je·hoiʹa·da"],
    "chosenOffspring": "Uz·ziʹah",
    "prophets": ["E·liʹshah", "Jonah", "Hosea", "Amos"],
    "sons": ["Uz·ziʹah"],
  },
  {
    "kingNumber": 10,
    "kingName": "Uz·ziʹah",
    "kingNamePlain": "Uzziah",
    "age": 16,
    "startReignYear": "829 B.C.E.",
    "endReignYear": "777 B.C.E.",
    "highPriests": [
       "Az·a·riʹah II"
    ],
    "prophets": ["Micah", "Hosea", "Isaiah", "Joel (?)"],
    "chosenOffspring": "Joʹtham",
    "sons": ["Joʹtham"],
  },
  {
    "kingNumber": 11,
    "kingName": "Joʹtham",
    "kingNamePlain": "Jotham",
    "age": 25,
    "startReignYear": "777 B.C.E.",
    "endReignYear": "762 B.C.E.",
    "highPriests": [
       "Az·a·riʹah II"
    ],
    "prophets": ["Micah", "Hosea", "Isaiah"],
    "chosenOffspring": "Aʹhaz",
    "sons": ["Aʹhaz"],
  },
  {
    "kingNumber": 12,
    "kingName": "Aʹhaz",
    "kingNamePlain": "Ahaz",
    "age": 20,
    "startReignYear": "762 B.C.E.",
    "endReignYear": "746 B.C.E.",
    "highPriests": [
       "Urijah (?)"
    ],
    "prophets": ["Micah", "Hosea", "Isaiah"],
    "chosenOffspring": "Hez·e·kiʹah",
    "sons": ["Hez·e·kiʹah"],
  },
  {
    "kingNumber": 13,
    "kingName": "Hez·e·kiʹah",
    "kingNamePlain": "Hezekiah",
    "age": 25,
    "startReignYear": "746 B.C.E.",
    "endReignYear": "716 B.C.E.",
    "highPriests": ["Az·a·riʹah (II or III)"],
    "prophets": ["Micah", "Hosea", "Isaiah"],
    "chosenOffspring": "Ma·nasʹseh",
    "sons": ["Ma·nasʹseh"],
  },
  {
    "kingNumber": 14,
    "kingName": "Ma·nasʹseh",
    "kingNamePlain": "Manasseh",
    "age": 12,
    "startReignYear": "716 B.C.E.",
    "endReignYear": "661 B.C.E.",
    "highPriests": ["Az·a·riʹah (II or III)"],
    "chosenOffspring": "Aʹmon",
    "prophets": ["Isaiah (?)"],
    "sons": ["Aʹmon"],
  },
  {
    "kingNumber": 15,
    "kingName": "Aʹmon",
    "kingNamePlain": "Amon",
    "age": 22,
    "startReignYear": "661 B.C.E.",
    "endReignYear": "659 B.C.E.",
    "highPriests": ["Az·a·riʹah (II or III)"],
    "prophets": [],
    "chosenOffspring": "Jo·siʹah",
    "sons": ["Jo·siʹah"],
  },
  {
    "kingNumber": 16,
    "kingName": "Jo·siʹah",
    "kingNamePlain": "Josiah",
    "age": 8,
    "startReignYear": "659 B.C.E.",
    "endReignYear": "628 B.C.E.",
    "highPriests": ["Hilkiah"],
    "prophets": ["Zephaniah", "Jeremiah", "Huldah"],
    "chosenOffspring": "Je·hoiʹa·kim",
    "sons": ["Je·hoʹa·haz","Jo·haʹnan","Je·hoiʹa·kim","Zed·e·kiʹah"],
  },
  {
    "kingNumber": 17,
    "kingName": "Je·hoʹa·haz (Shalʹlum)",
    "kingNamePlain": "Jehoahaz",
    "age": 23,
    "startReignYear": "628 B.C.E.",
    "endReignYear": "628 B.C.E.",
    "highPriests": ["Hilkiah"],
    "prophets": ["Jeremiah"],
    "chosenOffspring": null,
    "sons": [],
  },
  {
    "kingNumber": 18,
    "kingName": "Je·hoiʹa·kim (E·liʹa·kim)",
    "kingNamePlain": "Jehoiakim",
    "age": 25,
    "startReignYear": "628 B.C.E.",
    "endReignYear": "618 B.C.E.",
    "highPriests": ["Hilkiah"],
    "prophets": ["Habakkuk (?), Jeremiah"],
    "chosenOffspring": "Je·hoiʹa·chin",
    "sons": ["Je·hoiʹa·chin"],
  },
  {
    "kingNumber": 19,
    "kingName": "Je·hoiʹa·chin (Jec·o·niʹah)",
    "kingNamePlain": "Jehoiachin",
    "age": 18,
    "startReignYear": "618 B.C.E.",
    "endReignYear": "617 B.C.E.",
    "highPriests": ["Hilkiah"],
    "prophets": ["Jeremiah"],
    "chosenOffspring": "Shealtiel",
    "sons": ["Shealtiel"],
  },
  {
    "kingNumber": 20,
    "kingName": "Zed·e·kiʹah",
    "kingNamePlain": "Zedekiah",
    "age": 21,
    "startReignYear": "617 B.C.E.",
    "endReignYear": "607 B.C.E.",
    "highPriests": ["Seraiah"],
    "prophets": ["Jeremiah", "Ezekiel"],
    "chosenOffspring": null,
    "sons": [],
  },
];